language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script: make
notifications:
    irc:
        channels:
          - "irc.freenode.org#gmqcc"
        template:
          - "[%{commit} : %{author}] %{message}"
          - "%{build_url}"
        skip_join: true
